version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 
      
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
        
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssql_order:/var/opt/mssql  # Persist SQL Server data
  
  authdb:
    container_name: authdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - "1444:1433"
    restart: always
    volumes:
      - mssql_auth:/var/opt/mssql  # Persist SQL Server data
    networks:
      - sqlnetwork
      
  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASSWORD=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
        
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro

  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=authdb,1444;Database=AuthDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - authdb
    ports:
      - "6005:8080"
      - "6065:8081"
    networks:
      - sqlnetwork
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6004:8080"
      - "6064:8081"

    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      
networks:
  sqlnetwork:
    driver: bridge